name: '🚀 - Feature Request'
title: '🚀 - '
description: Suggest a feature
labels: ['feature']
assignees: ddubrava

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        A proposed solution.
        Alternatives considered.
    validations:
      required: true

  - type: checkboxes
    id: library
    attributes:
      label: Library name
      options:
        - label: angular8-yandex-maps
        - label: angular-yandex-maps-v3
