name: '❓ - Help wanted'
title: '❓ - '
description: Help wanted
labels: ['help wanted']
assignees: ddubrava

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of the problem
    validations:
      required: true

  - type: checkboxes
    id: library
    attributes:
      label: Library name
      options:
        - label: angular8-yandex-maps
        - label: angular-yandex-maps-v3
