name: '❓ - Help wanted'
title: '❓ - '
description: Help wanted
labels: ['help wanted']
assignees: ddubrava

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of the problem
    validations:
      required: true
