name: GitHub Pages

on:
  push:
    tags:
      - '*'

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  deploy:
    name: Github pages deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm install

      - name: Generate documentation
        run: |
          npm run build:docs

      - name: Archive www Artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: dist/docsify

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: dist/docsify

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/docsify
          clean: true
